// <auto-generated />
namespace Olbrasoft.Travel.Data.Entity.Migrations.Routing
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Controll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Controll));
        
        string IMigrationMetadata.Id
        {
            get { return "201810160707296_Controll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
